a = int(input("Enter first  no "))
b = int(input("Enter second no "))
print(f"sum of {a} and {b} is {a+b}")
print(f"substraction of {a} and {b} is {a-b}")
print(f"multiplication of {a} and {b} is {a*b}")
print(f"division of {a} and {b} is {a/b}")
